### ISSUE TITLE
Default detection_rules_directory value and duplicate rule entries

### ISSUE THREAD

**Issue by crahan** [krakow2600/atomic-threat-coverage#101]
Thank you for starting this project. It's the first I've come across that not only brings together different analytics resources but allows you to generate documentation in a dynamic and reproducable way!

As I was going over the code I had some questions regarding the default `detection_rules_directory` config value. The default appears to point to the `.yml` files stored at the root of the `detection_rules` folder. However, it appears that all the rules are duplicated in `detection_rules/all-windows-rules/` as well. Could you elaborate on why the same files are stored 2 different locations?

Also, is there a particular reason why the detection rules logic doesn't directly pull from the rules folder in the `Neo23x0/sigma` project when generating the documentation? For example `win_wmi_persistence.yml` was updated in the originel `sigma` submodule (one of the detection keywords was commented out due to too many false positive with HP Health Driver). I'd like to ensure that when I generate a new set of Markdown files that the most recent Sigma rules are being used.

Thanks for providing a better understanding on how the underlying logic works!

**Comment by yugoslavskiy** [comment]
Hello @crahan ! 

Thank you for the interest to our project.

Multiple directories with duplicate rules are left from dev branch. As you've noticed, they are not used. The reason we have multiple directories is that for now our script grabs Detection Rules only from 1 directory. And as you know, Sigma has multiple directories for rules. So we just copied all windows-related rules into one directory and processed them from there. Then one of these directories wasn't deleted after testing. But I've deleted it already (:

We've created an issue in our internal GitLab to make it work with multiple directories for Detection Rules and probably will do the same for Triggers. It will be implemented during next sprint.

I've made dirty hack / hot fix for this issue, adding this line to Makefile: 

```
setup:
	@echo "[*] Updating 3rd party repository"
	git submodule init
	git submodule update
	git submodule foreach git pull origin master
	cp -r detection_rules/sigma/rules/windows/*/*.yml detection_rules/ # <---- THIS
```

So it updates all submodules, incl. Sigma, then copies all windows related rules into default Detection Rules directory (detection_rules).
Each time during execution of `make` all rules will be rewritten with new ones from updated Sigma master branch.

Detection Rule in Markdown have been [updated](https://github.com/krakow2600/atomic-threat-coverage/blob/master/Atomic_Threat_Coverage/Detection_Rules/win_wmi_persistence.md) according to updated [sigma rule](https://github.com/krakow2600/atomic-threat-coverage/blob/master/detection_rules/win_wmi_persistence.yml).

Anyway, as I said, we will fix this issue in a proper way next sprint.

Thank you and have a great day!
