### ISSUE TITLE
Feature request: integration of Mordor project

### ISSUE THREAD

**Issue by 2xyo** [krakow2600/atomic-threat-coverage#109]
The Mordor is a repo of pre-recorded security events generated by emulated adversarial techniques in the form of JSON files for easy consumption : 

- announcement: https://twitter.com/Cyb3rWard0g/status/1109270967703011328
- project : https://github.com/Cyb3rWard0g/mordor 
- doc: https://mordor.readthedocs.io/en/latest/ 

It would be great to link techniques to this dataset.  

Sample T1003: https://github.com/Cyb3rWard0g/mordor/blob/master/small_datasets/windows/credential_access/credential_dumping_T1003/credentials_from_ad/empire_dcsync.md

**Comment by yugoslavskiy** [comment]
Great Idea! We've added this data to our Elastic Stack for Dashboard demonstrations :) Thanks for proposal!
