### ISSUE TITLE
Credentials?

### ISSUE THREAD

**Issue by vaggosvonkarajan** [krakow2600/atomic-threat-coverage#133]
Are you providing the credentials ?  i Installed the docker image but is asking for confluence credentials at some point and i cannot continue

**Comment by yugoslavskiy** [comment]
Hello @vaggosvonkarajan ! You probably missed step 5 of demo with docker:

```
5. Update scripts/config.yml with links to your own Confluence node (following instructions inside the default config)
```

You need to put links to your own Confluence to use it as export for ATC. You need to use your own credentials for it.
